spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/to_do_db
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: SQL_SERVER
    database-platform: org.hibernate.dialect.MariaDBDialect

  security:
    user:
      name: sashi
      password: password
      roles: ADMIN, USER, MANAGER

  logging:
    level:
      org.springframework.security: DEBUG



application:

server:
  port: 8080